/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as InternationalToursRouteImport } from './routes/international-tours'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarRentalsRouteImport } from './routes/car-rentals'
import { Route as BusRentalsRouteImport } from './routes/bus-rentals'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalToursRoute = InternationalToursRouteImport.update({
  id: '/international-tours',
  path: '/international-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRentalsRoute = CarRentalsRouteImport.update({
  id: '/car-rentals',
  path: '/car-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const BusRentalsRoute = BusRentalsRouteImport.update({
  id: '/bus-rentals',
  path: '/bus-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/bus-rentals': typeof BusRentalsRoute
  '/car-rentals': typeof CarRentalsRoute
  '/contact': typeof ContactRoute
  '/international-tours': typeof InternationalToursRoute
  '/tours': typeof ToursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/bus-rentals': typeof BusRentalsRoute
  '/car-rentals': typeof CarRentalsRoute
  '/contact': typeof ContactRoute
  '/international-tours': typeof InternationalToursRoute
  '/tours': typeof ToursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/bus-rentals': typeof BusRentalsRoute
  '/car-rentals': typeof CarRentalsRoute
  '/contact': typeof ContactRoute
  '/international-tours': typeof InternationalToursRoute
  '/tours': typeof ToursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/bus-rentals'
    | '/car-rentals'
    | '/contact'
    | '/international-tours'
    | '/tours'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/bus-rentals'
    | '/car-rentals'
    | '/contact'
    | '/international-tours'
    | '/tours'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/bus-rentals'
    | '/car-rentals'
    | '/contact'
    | '/international-tours'
    | '/tours'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  BusRentalsRoute: typeof BusRentalsRoute
  CarRentalsRoute: typeof CarRentalsRoute
  ContactRoute: typeof ContactRoute
  InternationalToursRoute: typeof InternationalToursRoute
  ToursRoute: typeof ToursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-tours': {
      id: '/international-tours'
      path: '/international-tours'
      fullPath: '/international-tours'
      preLoaderRoute: typeof InternationalToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-rentals': {
      id: '/car-rentals'
      path: '/car-rentals'
      fullPath: '/car-rentals'
      preLoaderRoute: typeof CarRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bus-rentals': {
      id: '/bus-rentals'
      path: '/bus-rentals'
      fullPath: '/bus-rentals'
      preLoaderRoute: typeof BusRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  BusRentalsRoute: BusRentalsRoute,
  CarRentalsRoute: CarRentalsRoute,
  ContactRoute: ContactRoute,
  InternationalToursRoute: InternationalToursRoute,
  ToursRoute: ToursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
